blank_issues_enabled: false
contact_links:
  - name: 💬 Questions générales (Teams)
    url: https://teams.microsoft.com
    about: Pour toute question ne correspondant pas à un bug ou une fonctionnalité, contactez Hamza sur Teams.
